In [1]:
import numpy as np

In [2]:
u = np.array([
    [1],
    [2],
    [3],
])

In [3]:
v = np.array([
    [4],
    [5],
    [6],
])

In [4]:
u

array([[1],
       [2],
       [3]])

In [5]:
v

array([[4],
       [5],
       [6]])

In [11]:
u.T @ v

array([[32]])

In [16]:
u.T * v # Brordcasrting

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [17]:
u @ v.T

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [20]:
u * v

array([[ 4],
       [10],
       [18]])

In [21]:
v.T @ u

array([[32]])

In [22]:
v @ u.T

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [23]:
u.T @ v

array([[32]])

In [24]:
v.T @ u

array([[32]])

In [26]:
u @ v.T

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [27]:
v.T.shape

(1, 3)

In [28]:
u.shape

(3, 1)

In [29]:
u * v

array([[ 4],
       [10],
       [18]])

In [53]:
import numpy as np
import matplotlib.pyplot as plt

N = 10
D = 3
X = np.zeros((N, D))
X[:,0] = 1 # bias term
X[:5,1] = 1
X[5:,2] = 1
Y = np.array([0]*5 + [1]*5).reshape(-1, 1)

# print X so you know what it looks like
# print("X:", X)

# won't work!
# w = np.linalg.solve(X.T.dot(X), X.T.dot(Y))

# let's try gradient descent
w = np.random.randn(D, 1)

learning_rate = 0.001
for t in range(10):
    # update w
    Yhat = X.dot(w)
    print(Yhat.shape)
    
    delta = Yhat - Y
    print(delta)
    
    w = w - learning_rate*X.T.dot(delta)
    
    break
    
print(w)

(10, 1)
[[ 0.08991456]
 [ 0.08991456]
 [ 0.08991456]
 [ 0.08991456]
 [ 0.08991456]
 [-2.35374294]
 [-2.35374294]
 [-2.35374294]
 [-2.35374294]
 [-2.35374294]]
[[-1.15710828]
 [ 1.25789241]
 [-0.1735468 ]]


In [49]:
Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [45]:
Y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])